### ISSUE TITLE
Task manager

### ISSUE THREAD

**Issue by afilipov1** [HQC-Team-Labyrinth-2/Labyrinth-2#1]
# TODO List
- [x] distribute tasks 
- [x] creating teams for unit testing
- [x] creating 3 branches for every team, holding their architecture
- [ ] run code coverage
